### ISSUE TITLE
Messages are not treated as player messages

### ISSUE THREAD

**Issue by Whitebrim** [stanlystark/SimpleChat#4]
Discord mods search logs for player messages and relays them to discord. But formatted messages from SimpleChat are not treated as player messages, but as plugin output.

https://github.com/hypherionmc/sdlink/issues/29
https://github.com/axieum/minecord/issues/86

**Comment by BANanaD3V** [comment]
bump, doesnt work with https://github.com/1-nkl/Discord4FabricRU. (discord4fabric fork in russian thats updated for 1.20.1, doesnt work with discord4fabric aswell)

**Comment by stanlystark** [comment]
Integration with Discord is not planned yet.

**Comment by Whitebrim** [comment]
> Integration with Discord is not planned yet.

You don't need to do integration. discord plugins' devs are doing integrations. You just need to format output to be parsable by other plugins, not only by minecraft.

**Comment by stanlystark** [comment]
> > Integration with Discord is not planned yet.
> 
> You don't need to do integration. discord plugins' devs are doing integrations. You just need to format output to be parsable by other plugins, not only by minecraft.

На самом деле я силен в java так, как следовало бы для полноценной разработки мода, я всего лишь добавляю посильные мне функции и пытаюсь поддерживать мод на новых версиях. Возможно в будущем я сделаю чтобы всё работало нормально, но не сейчас :)
